---
title: "tidytuesday_artwork"
author: "Margaux Sleckman"
date: "1/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }

#install.packages("tidytuesdayR")
install.packages("dplyr")
library(tidytuesdayR)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidytext)

```

```{r get_data}

tuesdata <- tidytuesdayR::tt_load(2021, week = 3)

```

```{r }

artists_df <- data.frame(tuesdata$artists)
artwork_df <- data.frame(tuesdata$artwork)

glimpse(artwork_df)
```

```{r histogram}


artwork_df %>% 
  ggplot(aes(year))+
  geom_histogram(alpha = 0.8, fill = "midnightblue")

```

```{r post1750}

tate_df <- artwork_df %>%
  filter(year > 1750) %>%
  select(year, medium) %>%
  na.omit() %>%
  arrange(year)

tate_df
```

```{r tokens}

tate_df %>%
  unnest_tokens(word, medium) %>%
  count(word, sort = TRUE) %>% 
  anti_join(stop_words)

tate <- data.frame(tate_df %>%
  unnest_tokens(word, medium) %>%
  count(word, sort = TRUE) %>% 
  anti_join(stop_words)
  )

```



```{r model_building}

install.packages("tidymodels")
library(tidymodels)

set.seed(123)
art_split <- initial_split(tate_df, strata = year)
art_train <- training(art_split)
art_test <- testing(art_split)

set.seed(234)
art_folds <- vfold_cv(art_train, strata = year)
art_folds

```



```{r preprocess}

install.packages("textrecipes")
library(textrecipes)

art_rec <- recipe(year ~ medium, data = art_train) %>%
  step_tokenize(medium) %>%
  step_stopwords(medium) %>%
  step_tokenfilter(medium, max_tokens = 500) %>%
  step_tfidf(medium)


```

